// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  htbSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // scans docs/
    },
  ],
};

export default sidebars;
